name: Build and Test

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./
  runs-on: ubuntu-latest

jobs:
  setup:
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

  build:
    needs: setup

    steps:
    - name: Use workspace from setup
      run: echo "Workspace setup complete"
      
    - name: Download dependencies
      run: go mod download

    - name: Build application
      run: go build ./...

  test:
    needs: build

    steps:
    - name: Use workspace from setup
      run: echo "Workspace setup complete"
      
    - name: Run tests
      run: make test
